name: Release

on:
  workflow_dispatch:
  release:
    types: published

jobs:
  run:
    runs-on: ubuntu-20.04

    steps:
    - name: Dependencies
      run: |
        mkdir -p /usr/share/man/man1
        sudo apt update
        sudo apt install -y octave debhelper dh-octave devscripts equivs fakeroot
        sudo octave --eval 'pkg install -global -forge generate_html'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Package Octave
      run: make dist

    - name: Package Debian
      run: |
        sudo mk-build-deps --install --tool='apt-get --no-install-recommends --yes' debian/control
        fakeroot debian/rules binary
